// Limits on model turns and wall-clock orchestration time
const MAX_MODEL_TURNS_PER_MESSAGE = 8;
const MAX_ORCHESTRATION_WALL_CLOCK_MS = 120000;

// Sandbox runtime configuration
const SANDBOX_IMAGE_TAG = 'public.ecr.aws/aws-cli/aws-cli:2.15.30';
const SANDBOX_DEFAULT_MEMORY_BYTES = 536870912; // 512 MB
const SANDBOX_DEFAULT_NANO_CPUS = 1000000000; // 1 vCPU
const SANDBOX_DEFAULT_PIDS_LIMIT = 64;

module.exports = {
  MAX_MODEL_TURNS_PER_MESSAGE,
  MAX_ORCHESTRATION_WALL_CLOCK_MS,
  SANDBOX_IMAGE_TAG,
  SANDBOX_DEFAULT_MEMORY_BYTES,
  SANDBOX_DEFAULT_NANO_CPUS,
  SANDBOX_DEFAULT_PIDS_LIMIT,
};
