// AuditLog action types: what event occurred
const AUDIT_ACTIONS = Object.freeze({
  LOOKUP_EXECUTED: 'LOOKUP_EXECUTED',
  COMMAND_PROPOSED: 'COMMAND_PROPOSED',
  COMMAND_CONFIRMED: 'COMMAND_CONFIRMED',
  COMMAND_CANCELLED: 'COMMAND_CANCELLED',
  COMMAND_EXECUTED: 'COMMAND_EXECUTED',
  COMMAND_REJECTED: 'COMMAND_REJECTED',
  SESSION_CAP_EXCEEDED: 'SESSION_CAP_EXCEEDED',
});

// AuditLog outcome: the result of that action
const AUDIT_OUTCOMES = Object.freeze({
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
  REJECTED: 'REJECTED',
  CAPPED: 'CAPPED',
  CANCELLED: 'CANCELLED',
});

module.exports = { AUDIT_ACTIONS, AUDIT_OUTCOMES };
